// lib/data.js
// Nova Store — Dummy Data
// Product data normalized for every category.

const unsplashImage = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&h=900&q=80`;

const productPhotos = {
  "iPhone 15 Pro Max": unsplashImage("photo-1695048133142-1a20484d2569"),
  "iPhone 15 Pro Max - Back": unsplashImage("photo-1592750475338-74b7b21085ab"),
  "Galaxy S24 Ultra": unsplashImage("photo-1610945265064-0e34e5519bbf"),
  "Xiaomi 14 Pro": unsplashImage("photo-1598327105666-5b89351aff97"),
  "Google Pixel 8": unsplashImage("photo-1511707171634-5f897ff02aa9"),
  "OnePlus 12": unsplashImage("photo-1565849904461-04a58ad377e0"),
  "MacBook Pro 14": unsplashImage("photo-1517336714731-489689fd1ca8"),
  "Dell XPS 15": unsplashImage("photo-1593642632823-8f785ba67e45"),
  "ROG Zephyrus G14": unsplashImage("photo-1603302576837-37561b2e2302"),
  "HP Spectre x360": unsplashImage("photo-1541807084-5c52b6b3adef"),
  "ThinkPad X1 Carbon": unsplashImage("photo-1496181133206-80ce9b88a853"),
  "iPad Pro 12.9": unsplashImage("photo-1544244015-0df4b3ffc6b0"),
  "Galaxy Tab S9": unsplashImage("photo-1561154464-82e9adf32764"),
  "iPad Air 5": unsplashImage("photo-1585790050230-5dd28404ccb9"),
  "Lenovo Tab P11 Pro": unsplashImage("photo-1589739900243-4b52cd9b104e"),
  "Sony WH-1000XM5": unsplashImage("photo-1505740420928-5e560c06d30e"),
  "AirPods Pro 2": unsplashImage("photo-1600294037681-c80b4cb5b434"),
  "JBL Flip 6": unsplashImage("photo-1545454675-3531b543be5d"),
  "Bose QuietComfort Ultra": unsplashImage("photo-1546435770-a3e426bf472b"),
  "Apple Watch Series 9": unsplashImage("photo-1434493789847-2f02dc6ca35d"),
  "Galaxy Watch 6": unsplashImage("photo-1579586337278-3befd40fd17a"),
  "Garmin Venu 3": unsplashImage("photo-1523275335684-37898b6baf30"),
  "Xiaomi Watch S3": unsplashImage("photo-1524805444758-089113d48a6d"),
  "PlayStation 5 Slim": unsplashImage("photo-1606144042614-b2417e99c4e3"),
  "Xbox Series X": unsplashImage("photo-1621259182978-fbf93132d53d"),
  "Nintendo Switch OLED": unsplashImage("photo-1578303512597-81e6cc155b3e"),
  "Razer DeathAdder V3": unsplashImage("photo-1527814050087-3793815479db"),
  "Arctis Nova Pro": unsplashImage("photo-1484704849700-f032a568e944"),
  "Canon EOS R6 Mark II": unsplashImage("photo-1516035069371-29a1b244cc32"),
  "Sony Alpha a7 IV": unsplashImage("photo-1581591546314-528384aab67c"),
  "Fujifilm X-T5": unsplashImage("photo-1495707902641-75cac588d2e9"),
  "GoPro HERO12": unsplashImage("photo-1564466809058-bf4114d55352"),
  "Anker PowerCore 20000": unsplashImage("photo-1604160687800-f7799a525a33"),
  "Belkin MagSafe Charger": unsplashImage("photo-1622445268465-8428a36a2a9e"),
  "Spigen Tough Armor Case": unsplashImage("photo-1601784551446-20c9e07cdbdb"),
  "Anker 3-in-1 Station": unsplashImage("photo-1586953208448-b95a79798f07"),
  "UGREEN USB-C Hub": unsplashImage("photo-1625948515291-69613efd103f"),
};

const getProductImage = (seed) => productPhotos[seed];

export const products = [
  // ---------------- Smartphones ----------------
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    category: "smartphones",
    brand: "Apple",
    price: 1199,
    oldPrice: 1299,
    discount: 8,
    rating: 4.8,
    reviews: 342,
    stock: 28,
    image: getProductImage("iPhone 15 Pro Max"),
    images: [
      getProductImage("iPhone 15 Pro Max"),
      getProductImage("iPhone 15 Pro Max - Back"),
    ],
    description:
      "The latest iPhone with the A17 Pro chip, a titanium design, and a professional 48MP camera system.",
    specs: {
      screen: "6.7 inch OLED",
      storage: "256GB",
      ram: "8GB",
      battery: "4441mAh",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    category: "smartphones",
    brand: "Samsung",
    price: 1099,
    oldPrice: 1199,
    discount: 8,
    rating: 4.7,
    reviews: 289,
    stock: 34,
    image: getProductImage("Galaxy S24 Ultra"),
    images: [getProductImage("Galaxy S24 Ultra")],
    description:
      "Flagship phone with an S Pen, 200MP camera, and Dynamic AMOLED display.",
    specs: {
      screen: "6.8 inch AMOLED",
      storage: "512GB",
      ram: "12GB",
      battery: "5000mAh",
    },
    isNew: true,
    isFeatured: false,
  },
  {
    id: 3,
    name: "Xiaomi 14 Pro",
    category: "smartphones",
    brand: "Xiaomi",
    price: 749,
    oldPrice: 849,
    discount: 12,
    rating: 4.5,
    reviews: 156,
    stock: 52,
    image: getProductImage("Xiaomi 14 Pro"),
    images: [getProductImage("Xiaomi 14 Pro")],
    description: "Powerful performance with Snapdragon 8 Gen 3 and Leica lenses.",
    specs: {
      screen: "6.73 inch AMOLED",
      storage: "256GB",
      ram: "12GB",
      battery: "4880mAh",
    },
    isNew: false,
    isFeatured: true,
  },
  {
    id: 4,
    name: "Google Pixel 8",
    category: "smartphones",
    brand: "Google",
    price: 699,
    oldPrice: 699,
    discount: 0,
    rating: 4.6,
    reviews: 201,
    stock: 19,
    image: getProductImage("Google Pixel 8"),
    images: [getProductImage("Google Pixel 8")],
    description: "A clean Android experience with an AI-powered camera.",
    specs: {
      screen: "6.2 inch OLED",
      storage: "128GB",
      ram: "8GB",
      battery: "4575mAh",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 5,
    name: "OnePlus 12",
    category: "smartphones",
    brand: "OnePlus",
    price: 799,
    oldPrice: 899,
    discount: 11,
    rating: 4.6,
    reviews: 98,
    stock: 41,
    image: getProductImage("OnePlus 12"),
    images: [getProductImage("OnePlus 12")],
    description: "100W fast charging and flagship Snapdragon 8 Gen 3 performance.",
    specs: {
      screen: "6.82 inch AMOLED",
      storage: "256GB",
      ram: "16GB",
      battery: "5400mAh",
    },
    isNew: true,
    isFeatured: false,
  },

  // ---------------- Laptops ----------------
  {
    id: 6,
    name: 'MacBook Pro 14" M3',
    category: "laptops",
    brand: "Apple",
    price: 1999,
    oldPrice: 2199,
    discount: 9,
    rating: 4.9,
    reviews: 412,
    stock: 15,
    image: getProductImage("MacBook Pro 14"),
    images: [getProductImage("MacBook Pro 14")],
    description: "Exceptional M3 Pro performance with a Liquid Retina XDR display.",
    specs: {
      cpu: "Apple M3 Pro",
      ram: "18GB",
      storage: "512GB SSD",
      screen: "14.2 inch",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 7,
    name: "Dell XPS 15",
    category: "laptops",
    brand: "Dell",
    price: 1599,
    oldPrice: 1799,
    discount: 11,
    rating: 4.6,
    reviews: 187,
    stock: 22,
    image: getProductImage("Dell XPS 15"),
    images: [getProductImage("Dell XPS 15")],
    description: "A complete laptop for professionals with an InfinityEdge OLED display.",
    specs: {
      cpu: "Intel Core i7-13700H",
      ram: "16GB",
      storage: "1TB SSD",
      screen: "15.6 inch",
    },
    isNew: false,
    isFeatured: true,
  },
  {
    id: 8,
    name: "ASUS ROG Zephyrus G14",
    category: "laptops",
    brand: "ASUS",
    price: 1749,
    oldPrice: 1899,
    discount: 8,
    rating: 4.7,
    reviews: 143,
    stock: 12,
    image: getProductImage("ROG Zephyrus G14"),
    images: [getProductImage("ROG Zephyrus G14")],
    description: "Lightweight gaming laptop with Ryzen 9 and RTX 4060 graphics.",
    specs: {
      cpu: "AMD Ryzen 9 7940HS",
      ram: "16GB",
      storage: "1TB SSD",
      gpu: "RTX 4060",
    },
    isNew: true,
    isFeatured: false,
  },
  {
    id: 9,
    name: "HP Spectre x360",
    category: "laptops",
    brand: "HP",
    price: 1399,
    oldPrice: 1499,
    discount: 7,
    rating: 4.5,
    reviews: 96,
    stock: 27,
    image: getProductImage("HP Spectre x360"),
    images: [getProductImage("HP Spectre x360")],
    description: "Convertible laptop with an elegant design and OLED touch display.",
    specs: {
      cpu: "Intel Core i7-1355U",
      ram: "16GB",
      storage: "512GB SSD",
      screen: "13.5 inch",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 10,
    name: "Lenovo ThinkPad X1 Carbon",
    category: "laptops",
    brand: "Lenovo",
    price: 1549,
    oldPrice: 1699,
    discount: 9,
    rating: 4.7,
    reviews: 210,
    stock: 18,
    image: getProductImage("ThinkPad X1 Carbon"),
    images: [getProductImage("ThinkPad X1 Carbon")],
    description: "Lightweight and durable, ideal for business users and developers.",
    specs: {
      cpu: "Intel Core i7-1365U",
      ram: "16GB",
      storage: "1TB SSD",
      screen: "14 inch",
    },
    isNew: false,
    isFeatured: true,
  },

  // ---------------- Tablets ----------------
  {
    id: 11,
    name: 'iPad Pro 12.9" M2',
    category: "tablets",
    brand: "Apple",
    price: 1099,
    oldPrice: 1199,
    discount: 8,
    rating: 4.8,
    reviews: 267,
    stock: 24,
    image: getProductImage("iPad Pro 12.9"),
    images: [getProductImage("iPad Pro 12.9")],
    description: "Apple's most powerful tablet with an M2 chip and Liquid Retina XDR display.",
    specs: {
      screen: "12.9 inch",
      storage: "256GB",
      ram: "8GB",
      chip: "Apple M2",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 12,
    name: "Samsung Galaxy Tab S9",
    category: "tablets",
    brand: "Samsung",
    price: 799,
    oldPrice: 899,
    discount: 11,
    rating: 4.6,
    reviews: 134,
    stock: 31,
    image: getProductImage("Galaxy Tab S9"),
    images: [getProductImage("Galaxy Tab S9")],
    description:
      "Flagship Android tablet with a water-resistant AMOLED display and included S Pen.",
    specs: {
      screen: "11 inch AMOLED",
      storage: "128GB",
      ram: "8GB",
      battery: "8400mAh",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 13,
    name: "iPad Air 5",
    category: "tablets",
    brand: "Apple",
    price: 599,
    oldPrice: 649,
    discount: 8,
    rating: 4.7,
    reviews: 198,
    stock: 40,
    image: getProductImage("iPad Air 5"),
    images: [getProductImage("iPad Air 5")],
    description: "An ideal balance of performance and price with the M1 chip.",
    specs: {
      screen: "10.9 inch",
      storage: "64GB",
      ram: "8GB",
      chip: "Apple M1",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 14,
    name: "Lenovo Tab P11 Pro",
    category: "tablets",
    brand: "Lenovo",
    price: 399,
    oldPrice: 449,
    discount: 11,
    rating: 4.3,
    reviews: 67,
    stock: 45,
    image: getProductImage("Lenovo Tab P11 Pro"),
    images: [getProductImage("Lenovo Tab P11 Pro")],
    description: "Versatile tablet with an OLED display and JBL speakers.",
    specs: {
      screen: "11.2 inch OLED",
      storage: "128GB",
      ram: "6GB",
      battery: "8600mAh",
    },
    isNew: false,
    isFeatured: false,
  },

  // ---------------- Audio ----------------
  {
    id: 15,
    name: "Sony WH-1000XM5",
    category: "audio",
    brand: "Sony",
    price: 399,
    oldPrice: 449,
    discount: 11,
    rating: 4.9,
    reviews: 523,
    stock: 60,
    image: getProductImage("Sony WH-1000XM5"),
    images: [getProductImage("Sony WH-1000XM5")],
    description: "Top-tier noise-cancelling headphones with exceptional sound quality.",
    specs: {
      type: "Over-ear Wireless",
      battery: "30 hours",
      noiseCancelling: "Yes",
    },
    isNew: false,
    isFeatured: true,
  },
  {
    id: 16,
    name: "Apple AirPods Pro 2",
    category: "audio",
    brand: "Apple",
    price: 249,
    oldPrice: 279,
    discount: 11,
    rating: 4.8,
    reviews: 678,
    stock: 85,
    image: getProductImage("AirPods Pro 2"),
    images: [getProductImage("AirPods Pro 2")],
    description: "Wireless earbuds with active noise cancellation and spatial audio.",
    specs: {
      type: "In-ear Wireless",
      battery: "6 hours (30 with case)",
      noiseCancelling: "Yes",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 17,
    name: "JBL Flip 6",
    category: "audio",
    brand: "JBL",
    price: 129,
    oldPrice: 149,
    discount: 13,
    rating: 4.6,
    reviews: 234,
    stock: 72,
    image: getProductImage("JBL Flip 6"),
    images: [getProductImage("JBL Flip 6")],
    description: "Water-resistant portable speaker with powerful, balanced sound.",
    specs: {
      type: "Portable Speaker",
      battery: "12 hours",
      waterproof: "IP67",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 18,
    name: "Bose QuietComfort Ultra",
    category: "audio",
    brand: "Bose",
    price: 429,
    oldPrice: 429,
    discount: 0,
    rating: 4.8,
    reviews: 156,
    stock: 33,
    image: getProductImage("Bose QuietComfort Ultra"),
    images: [getProductImage("Bose QuietComfort Ultra")],
    description: "Exceptional comfort and world-class noise cancellation.",
    specs: {
      type: "Over-ear Wireless",
      battery: "24 hours",
      noiseCancelling: "Yes",
    },
    isNew: true,
    isFeatured: false,
  },

  // ---------------- Smart Watches ----------------
  {
    id: 19,
    name: "Apple Watch Series 9",
    category: "smartwatches",
    brand: "Apple",
    price: 429,
    oldPrice: 449,
    discount: 4,
    rating: 4.8,
    reviews: 389,
    stock: 47,
    image: getProductImage("Apple Watch Series 9"),
    images: [getProductImage("Apple Watch Series 9")],
    description: "Complete smartwatch with an S9 chip and advanced health sensors.",
    specs: { screen: "45mm OLED", battery: "18 hours", waterResistant: "50m" },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 20,
    name: "Samsung Galaxy Watch 6",
    category: "smartwatches",
    brand: "Samsung",
    price: 329,
    oldPrice: 369,
    discount: 11,
    rating: 4.6,
    reviews: 178,
    stock: 39,
    image: getProductImage("Galaxy Watch 6"),
    images: [getProductImage("Galaxy Watch 6")],
    description: "Accurate health tracking with a bright AMOLED display and classic design.",
    specs: {
      screen: "44mm AMOLED",
      battery: "40 hours",
      waterResistant: "50m",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 21,
    name: "Garmin Venu 3",
    category: "smartwatches",
    brand: "Garmin",
    price: 449,
    oldPrice: 449,
    discount: 0,
    rating: 4.7,
    reviews: 92,
    stock: 21,
    image: getProductImage("Garmin Venu 3"),
    images: [getProductImage("Garmin Venu 3")],
    description: "Ideal for sports enthusiasts with up to 14 days of battery life.",
    specs: {
      screen: "45mm AMOLED",
      battery: "14 days",
      waterResistant: "5 ATM",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 22,
    name: "Xiaomi Watch S3",
    category: "smartwatches",
    brand: "Xiaomi",
    price: 149,
    oldPrice: 179,
    discount: 17,
    rating: 4.4,
    reviews: 61,
    stock: 55,
    image: getProductImage("Xiaomi Watch S3"),
    images: [getProductImage("Xiaomi Watch S3")],
    description: "Customizable smartwatch design at an accessible price.",
    specs: {
      screen: "1.43 inch AMOLED",
      battery: "15 days",
      waterResistant: "5 ATM",
    },
    isNew: true,
    isFeatured: false,
  },

  // ---------------- Gaming ----------------
  {
    id: 23,
    name: "PlayStation 5 Slim",
    category: "gaming",
    brand: "Sony",
    price: 499,
    oldPrice: 549,
    discount: 9,
    rating: 4.9,
    reviews: 812,
    stock: 14,
    image: getProductImage("PlayStation 5 Slim"),
    images: [getProductImage("PlayStation 5 Slim")],
    description: "A new generation of gaming with ultra performance and sleek design.",
    specs: {
      storage: "1TB SSD",
      resolution: "4K",
      included: "1 DualSense Controller",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 24,
    name: "Xbox Series X",
    category: "gaming",
    brand: "Microsoft",
    price: 499,
    oldPrice: 499,
    discount: 0,
    rating: 4.8,
    reviews: 645,
    stock: 20,
    image: getProductImage("Xbox Series X"),
    images: [getProductImage("Xbox Series X")],
    description: "The most powerful Xbox console with true 4K and 120fps performance.",
    specs: { storage: "1TB SSD", resolution: "4K", included: "1 Controller" },
    isNew: false,
    isFeatured: true,
  },
  {
    id: 25,
    name: "Nintendo Switch OLED",
    category: "gaming",
    brand: "Nintendo",
    price: 349,
    oldPrice: 349,
    discount: 0,
    rating: 4.7,
    reviews: 421,
    stock: 33,
    image: getProductImage("Nintendo Switch OLED"),
    images: [getProductImage("Nintendo Switch OLED")],
    description: "Portable and home console with a vivid OLED screen.",
    specs: { screen: "7 inch OLED", storage: "64GB", battery: "4.5-9 hours" },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 26,
    name: "Razer DeathAdder V3",
    category: "gaming",
    brand: "Razer",
    price: 69,
    oldPrice: 79,
    discount: 13,
    rating: 4.6,
    reviews: 187,
    stock: 90,
    image: getProductImage("Razer DeathAdder V3"),
    images: [getProductImage("Razer DeathAdder V3")],
    description: "Lightweight gaming mouse with a high-precision sensor.",
    specs: { dpi: "30000", weight: "59g", connection: "Wireless" },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 27,
    name: "SteelSeries Arctis Nova Pro",
    category: "gaming",
    brand: "SteelSeries",
    price: 349,
    oldPrice: 379,
    discount: 8,
    rating: 4.7,
    reviews: 98,
    stock: 26,
    image: getProductImage("Arctis Nova Pro"),
    images: [getProductImage("Arctis Nova Pro")],
    description: "Professional gaming headset with surround sound and active noise cancellation.",
    specs: {
      type: "Wireless Gaming Headset",
      battery: "22 hours",
      noiseCancelling: "Yes",
    },
    isNew: true,
    isFeatured: false,
  },

  // ---------------- Cameras ----------------
  {
    id: 28,
    name: "Canon EOS R6 Mark II",
    category: "cameras",
    brand: "Canon",
    price: 2499,
    oldPrice: 2699,
    discount: 7,
    rating: 4.9,
    reviews: 76,
    stock: 9,
    image: getProductImage("Canon EOS R6 Mark II"),
    images: [getProductImage("Canon EOS R6 Mark II")],
    description: "Professional mirrorless camera with a 24MP sensor and 4K60 video.",
    specs: {
      sensor: "24.2MP Full-Frame",
      video: "4K 60fps",
      iso: "100-102400",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 29,
    name: "Sony Alpha a7 IV",
    category: "cameras",
    brand: "Sony",
    price: 2499,
    oldPrice: 2499,
    discount: 0,
    rating: 4.8,
    reviews: 112,
    stock: 11,
    image: getProductImage("Sony Alpha a7 IV"),
    images: [getProductImage("Sony Alpha a7 IV")],
    description: "Versatile hybrid camera with a 33MP sensor.",
    specs: { sensor: "33MP Full-Frame", video: "4K 60fps", iso: "100-51200" },
    isNew: false,
    isFeatured: true,
  },
  {
    id: 30,
    name: "Fujifilm X-T5",
    category: "cameras",
    brand: "Fujifilm",
    price: 1699,
    oldPrice: 1799,
    discount: 6,
    rating: 4.7,
    reviews: 88,
    stock: 15,
    image: getProductImage("Fujifilm X-T5"),
    images: [getProductImage("Fujifilm X-T5")],
    description: "Classic design with 40MP resolution and unique film color simulation.",
    specs: { sensor: "40.2MP APS-C", video: "6.2K 30fps", iso: "125-12800" },
    isNew: true,
    isFeatured: false,
  },
  {
    id: 31,
    name: "GoPro HERO12 Black",
    category: "cameras",
    brand: "GoPro",
    price: 399,
    oldPrice: 449,
    discount: 11,
    rating: 4.6,
    reviews: 267,
    stock: 48,
    image: getProductImage("GoPro HERO12"),
    images: [getProductImage("GoPro HERO12")],
    description: "Waterproof action camera with HyperSmooth stabilization.",
    specs: {
      video: "5.3K 60fps",
      waterproof: "10m",
      stabilization: "HyperSmooth 6.0",
    },
    isNew: true,
    isFeatured: false,
  },

  // ---------------- Mobile Accessories ----------------
  {
    id: 32,
    name: "Anker PowerCore 20000mAh",
    category: "accessories",
    brand: "Anker",
    price: 49,
    oldPrice: 59,
    discount: 17,
    rating: 4.7,
    reviews: 512,
    stock: 120,
    image: getProductImage("Anker PowerCore 20000"),
    images: [getProductImage("Anker PowerCore 20000")],
    description: "High-capacity power bank with fast charging for all your devices.",
    specs: {
      capacity: "20000mAh",
      output: "20W PD",
      ports: "2 USB-A, 1 USB-C",
    },
    isNew: false,
    isFeatured: true,
  },
  {
    id: 33,
    name: "Belkin MagSafe Charger",
    category: "accessories",
    brand: "Belkin",
    price: 39,
    oldPrice: 45,
    discount: 13,
    rating: 4.5,
    reviews: 178,
    stock: 90,
    image: getProductImage("Belkin MagSafe Charger"),
    images: [getProductImage("Belkin MagSafe Charger")],
    description: "Fast magnetic charger compatible with iPhone.",
    specs: { output: "15W", type: "Wireless MagSafe", cable: "1m" },
    isNew: true,
    isFeatured: false,
  },
  {
    id: 34,
    name: "Spigen Tough Armor Case",
    category: "accessories",
    brand: "Spigen",
    price: 19,
    oldPrice: 24,
    discount: 21,
    rating: 4.6,
    reviews: 342,
    stock: 210,
    image: getProductImage("Spigen Tough Armor Case"),
    images: [getProductImage("Spigen Tough Armor Case")],
    description: "Durable protective case with raised camera protection.",
    specs: {
      material: "TPU + Polycarbonate",
      dropProtection: "Military Grade",
    },
    isNew: false,
    isFeatured: false,
  },
  {
    id: 35,
    name: "Anker 3-in-1 Charging Station",
    category: "accessories",
    brand: "Anker",
    price: 79,
    oldPrice: 89,
    discount: 11,
    rating: 4.6,
    reviews: 143,
    stock: 65,
    image: getProductImage("Anker 3-in-1 Station"),
    images: [getProductImage("Anker 3-in-1 Station")],
    description: "One charger for your phone, watch, and earbuds at the same time.",
    specs: {
      output: "15W + 5W + 3W",
      compatibility: "iPhone, Apple Watch, AirPods",
    },
    isNew: true,
    isFeatured: true,
  },
  {
    id: 36,
    name: "UGREEN USB-C Hub 6-in-1",
    category: "accessories",
    brand: "UGREEN",
    price: 34,
    oldPrice: 39,
    discount: 13,
    rating: 4.5,
    reviews: 89,
    stock: 77,
    image: getProductImage("UGREEN USB-C Hub"),
    images: [getProductImage("UGREEN USB-C Hub")],
    description: "Multi-port hub that expands your mobile device capabilities.",
    specs: {
      ports: "HDMI, 2x USB-A, USB-C PD, SD, microSD",
      output: "100W PD",
    },
    isNew: false,
    isFeatured: false,
  },
];

export const getAllProducts = () => products;

export const getProductById = (id) => products.find((p) => p.id === Number(id));

export const getProductsByCategory = (categoryId) =>
  products.filter((p) => p.category === categoryId);

export const getFeaturedProducts = () => products.filter((p) => p.isFeatured);

export const getNewProducts = () => products.filter((p) => p.isNew);

export const searchProducts = (query) => {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q),
  );
};
